### ISSUE TITLE
KeyError: Caught KeyError in DataLoader worker process 0.

### ISSUE THREAD

**Issue by zyhsweety** [diffusion-face-relighting/difareli_code#15]
Dear authors,
When I run relight.py , I met problem.

`[#] Run from index of 0 to 1...
[[0, 1]]
['60922.jpg', '63252.jpg']
Traceback (most recent call last):
  File "relight.py", line 334, in <module>
    dat, model_kwargs = iter(subset_loader)
  File "/home/ubuntu/anaconda3/envs/dpm_sampling_deca/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/ubuntu/anaconda3/envs/dpm_sampling_deca/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/ubuntu/anaconda3/envs/dpm_sampling_deca/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/ubuntu/anaconda3/envs/dpm_sampling_deca/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/dpm_sampling_deca/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ubuntu/anaconda3/envs/dpm_sampling_deca/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/anaconda3/envs/dpm_sampling_deca/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/anaconda3/envs/dpm_sampling_deca/lib/python3.8/site-packages/torch/utils/data/dataset.py", line 272, in __getitem__
    return self.dataset[self.indices[idx]]
  File "/home/ubuntu/ZYH/difareli_code-main/sample_scripts/inference/../../guided_diffusion/dataloader/img_deca_datasets.py", line 308, in __getitem__
    out_dict["cond_params"] = np.concatenate([self.deca_params[query_img_name][k] for k in self.precomp_params_key])
  File "/home/ubuntu/ZYH/difareli_code-main/sample_scripts/inference/../../guided_diffusion/dataloader/img_deca_datasets.py", line 308, in <listcomp>
    out_dict["cond_params"] = np.concatenate([self.deca_params[query_img_name][k] for k in self.precomp_params_key])
KeyError: 'shape'`

The relevant code is below

` # Run from start->end idx
    start, end = int(args.idx[0]), int(args.idx[1])
    if end > n_subject:
        end = n_subject 
    if start >= n_subject: raise ValueError("[#] Start beyond the sample index")
    print(f"[#] Run from index of {start} to {end}...")
        
    for i in range(start, end):
        img_idx = all_img_idx[i]
        img_name = all_img_name[i]
        print(all_img_idx)
        print(img_name)
        dat = th.utils.data.Subset(dataset, indices=img_idx)
        subset_loader = th.utils.data.DataLoader(dat, batch_size=2,
                                            shuffle=False, num_workers=24)
                                   
        dat, model_kwargs = next(iter(subset_loader))
        print("#"*100)`

I don't know what caused this error

**Comment by lln0913** [comment]
I have the same problem. Have you solved it？

**Comment by zyhsweety** [comment]
@lln0913 I have solved it

**Comment by zyhsweety** [comment]
@lln0913 你可以修改params里的参数文件，把png改成jpg

**Comment by zyhsweety** [comment]
![image](https://github.com/diffusion-face-relighting/difareli_code/assets/64763982/6b5f4541-cdf5-41cd-a47a-40b18b3e88ea)

**Comment by zyhsweety** [comment]
json文件里也用jpg

**Comment by zyhsweety** [comment]
![image](https://github.com/diffusion-face-relighting/difareli_code/assets/64763982/f414dbdc-d95c-4d82-9854-81f219f71eb3)
